### ISSUE TITLE
node-remote not working in nwjs-v0.12.1-win-ia32

### ISSUE THREAD

**Issue by davewthompson** [nwjs/nw.js#3470]
Hey all,

I have the following line in my package.json file:

"main": "http://workstation123:9026/logs/",
"node-remote": "http://workstation123:9026/*,http://localhost:9026/*",

But my inline JS in my root.html file:
    
    <script>
        try {
            var gui = window.require('nw.gui');

Always throws a TypeError: undefined is not a function exception.

Is this a bug in the latest release?

**Comment by baconface** [comment]
Try:
```
"main": "http://workstation123:9026/logs/",
"node-remote": "workstation123:9026,<local>",
```

**Comment by davewthompson** [comment]
That's perfect. Works fine. Thank you!
