### ISSUE TITLE
global.window.nwDispatcher is undefined

### ISSUE THREAD

**Issue by zhenlovezhen2012** [nwjs/nw.js#4154]
global.window.nwDispatcher.requireNwGui()  not work in v0.13.0-beta2(mac);

global.window.nwDispatcher is undefined;

**Comment by ghostoy** [comment]
`nwDispatcher` is undocumented API and will not be supported by NW 0.13. Please use `require('nw.gui')` or just `nw`.

**Comment by niupanfeng** [comment]
I have changed the code as follows:
gui         =require('nw.gui')//global.window.nwDispatcher.requireNwGui()
but it not worked and got something wrong:can not find nw.gui

**Comment by ghostoy** [comment]
@niupanfeng `require('nw.gui')` should be working for all versions > 0.13.0. Could you post a test app that can reproduce the issue?

**Comment by niupanfeng** [comment]
@ghostoy 
## my environments:
nodejs: V6.1.0   64bit
npm: V3.8.6
OS:windows 10 x64
NW:nwjs-sdk-v0.16.0-win-ia32

## test steps:

1. create a project and add dependencies in package.json
    `"nw-notify": "^1.0.2"`
2. in project folder, exec `npm install` command

3. edit code in **{project_dir}\node_modules\nw-notify\index.js**
// gui         = global.window.nwDispatcher.requireNwGui()  --original
// gui         = window.require('nw.gui') 
   gui         = require('nw.gui') 

14. test
grag project folder to nw.exe

15. results:

  when I use `window.require('nw.gui')` ,errors as follows:
  **extensions::sendRequest:154 Uncaught cannot get current window; are you in background page/node context?**

  then,I use `require('nw.gui') `instead , errors as follows:
  **Uncaught Error: Cannot find module 'nw.gui'**

## test app source
[nwnotify.zip](https://github.com/nwjs/nw.js/files/380733/nwnotify.zip)


**Thanks a lot!**

**Comment by ghostoy** [comment]
@niupanfeng You are requiring nw.gui in Node context. I suggest you not to require `nw.gui` in your node modules. Instead passing `nw.gui` to your the module. For example, in `index.html`:

```javascript
var gui = require('nw.gui');
var nwNotify = require('nw-notify');
nwNotify.someFunc(nw, otherArguments);
```

In `nw-notify`, use `nw` argument instead of calling `require('nw.gui')`.
