### ISSUE TITLE
node-main no longer works (v0.10.0-rc1)

### ISSUE THREAD

**Issue by JovankaB** [nwjs/nw.js#1989]
If you try this example:
https://github.com/rogerwang/node-webkit/wiki/node-main

in nw v0.10.0-rc1, you get following error:
**Uncaught node.js Error 
TypeError: undefined is not a function**

It works in 0.9.2.
