### ISSUE TITLE
'Error: write EPROTO...' on making https request from node js context on Ubuntu

### ISSUE THREAD

**Issue by FahadQurashi49** [nwjs/nw.js#7886]
NWJS Version : 0.64.1
Operating System : Ubuntu 22.04

### Expected behavior

Should make https request successfully. working on previous version (checked on 0.58.0)

### Actual behavior

Throwing error on making https request.

> /home/user/Desktop/test/nwjs-sdk-v0.64.1-linux-x64-2/package.nw/index.js:20 Error: write EPROTO 00C3ADE3B57F0000:error:03000072:digital envelope routines:X509_PUBKEY_get0:decode error:../../third_party/node-nw/deps/openssl/openssl/crypto/x509/x_pubkey.c:458:
> at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)
> at __node_internal_errnoException (node:internal/errors:595:12)
>at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
> (anonymous) @ /home/user/Desktop/test/nwjs-sdk-v0.64.1-linux-x64-2/package.nw/index.js:20

### How to reproduce

run this code in nwjs with node context

index.js:
```
const https = require('node:https');

const options = {
  hostname: 'encrypted.google.com',
  port: 443,
  path: '/',
  method: 'GET'
};

const req = https.request(options, (res) => {
  console.log('statusCode:', res.statusCode);
  console.log('headers:', res.headers);

  res.on('data', (d) => {
    process.stdout.write(d);
  });
});

req.on('error', (e) => {
  console.error(e);
});
req.end();
```

package.json:
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "index.html",
  "node-main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
  }
}


```
code sample:
[nw-test.zip](https://github.com/nwjs/nw.js/files/8707990/nw-test.zip)

run this code inside nw's linux distribution and when app opens inspect background page and see console for node errors.

No crash dump files generated.
If I run the same code with node js on the same ubuntu system everything works perfectly.

**Comment by ayushmxn** [comment]
I'm using v0.66.1 on Ubuntu 22.04. After creating and running the [repro](https://github.com/ayushmxn/nw-repro/tree/dev-7886)

I'm getting this message in the terminal:
```
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
```

I'm getting this in the DevTools:
<img width="327" alt="image" src="https://user-images.githubusercontent.com/14110965/181689544-eb7498f7-9c70-4513-94d7-49f0422ee22a.png">

On running the JavaScript code snippet in Node 16.16, I get this in my terminal:
```shell
statusCode: 301
headers: {
  location: 'https://www.google.com/',
  'cross-origin-resource-policy': 'cross-origin',
  'x-content-type-options': 'nosniff',
  server: 'sffe',
  'content-length': '220',
  'x-xss-protection': '0',
  date: 'Fri, 29 Jul 2022 05:23:38 GMT',
  expires: 'Fri, 29 Jul 2022 05:53:38 GMT',
  'cache-control': 'public, max-age=1800',
  'content-type': 'text/html; charset=UTF-8',
  age: '727',
  'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"',
  connection: 'close'
}
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
```

Looks like HTTPS works in v0.66.1. Closing this for now. Ping me here if you have any other questions!
