### ISSUE TITLE
Use the same internal implementation of the browser native window 

### ISSUE THREAD

**Issue by rogerwang** [nwjs/nw.js#5875]
Currently the native window of NW application is implemented with the one from Chrome App. It need to be changed to the implementation of the Browser native window.

**Comment by Yonezpt** [comment]
Quick question regarding this subject, will this enable tabs to be opened/used or it will not change in this regard?

The advantage of this would be for them to have their own process instead of being iframes tied to the same window process. (#242)

**Comment by rogerwang** [comment]
Yes. It could help on enabling tabs as in Chrome browser.

**Comment by rogerwang** [comment]
The plan is to reuse the tab provided by Chrome browser and the API as well: https://developer.chrome.com/extensions/tabs . Please continue the discussion about tabs and make your proposal in #1136. Thanks.

**Comment by rogerwang** [comment]
0.35.4 is just released with a testing version of this. Please help testing it: https://nwjs.io/blog/v0.35.4/

**Comment by TheRealDannyyy** [comment]
Would very much appreciate a new page in the manual, regarding all the changes and new features.

Just in case, if something important needs to be changed inside my existing projects, in order to work with the new changes.

**Comment by elpeleq42** [comment]
My windows 10 blocked the startup of my application when I changed it to the last version(was working with v0.35.2)

**Comment by rogerwang** [comment]
Could you please provide a reproduce?

**Comment by Blatman** [comment]
OSX 10.13.6 (High Sierra)
Transparency broken - tried the new switch with 0.35.0-sdk and 0.35.5-sdk.
0.35.0 Works OK with --enable-features=nw2 --disable-gpu-compositing --force-cpu-draw
0.35.5 fails with --enable-features=nw2 --disable-gpu-compositing --force-cpu-draw
   will only show window bar.
If I remove compositing switch the window body will show but is broken
Each test done after app profile deleted.
Sample app attached with snaps -

[TransTest-simple.zip](https://github.com/nwjs/nw.js/files/2729372/TransTest-simple.zip)

Fail - 0.35.5
![fail-0 35 5-nw2](https://user-images.githubusercontent.com/11089335/50722777-1bf62600-10cc-11e9-972c-0f97908453f1.jpg)

OK - 0.35.0
![ok-0 35 0-nw2](https://user-images.githubusercontent.com/11089335/50722779-26182480-10cc-11e9-8cb1-2cce37176794.jpg)

Also noted that app used to open in center of screen but now opens in top left of screen.

**Comment by elpeleq42** [comment]
I can confirm status messages appearing on Windows 10 too.

**Comment by Blatman** [comment]
Corker - just tried above fixes with latest and all fixed OK (I tested OSX only).

Just noted - Quit App(CMD-Q ) from top OSX menu is not working - right-click quit from dock icon works OK.
This is reproducible with above test app and appears to have happened from the original new switch build.

**Comment by rogerwang** [comment]
Thanks. What does it do when it's broken?

**Comment by Blatman** [comment]
@rogerwang - thanks for close event fix it now allows 'tidyup' code to work however I find it now takes 2 clicks to close the window and CMD-Q on menu still not working.
I have attached a wee test app to demonstrate.
The simple mode should just invoke nw.App.closeAllWindows() on the close event but isn't honoured (neither is nw.App.quit()).
With the html and js start modes using the 'tidyup' code the first window close will do the tidy up (clear wkgFolder) but window remains open until second click.
Test app currently set for simple test.

[nw2test.zip](https://github.com/nwjs/nw.js/files/2740281/nw2test.zip)

Window position: center still not honouring.

Also noted that right-click context menu will offer saveas webpage option as per browser function - this didn't happen prior to switch.

<img width="427" alt="contextmenu-normal" src="https://user-images.githubusercontent.com/11089335/50891171-9f2cba00-13f3-11e9-904a-24cdc26c069a.png">

Cheers

**Comment by TheRealDannyyy** [comment]
@rogerwang With this new implementation, would it be possible to improve the transparent window feature?
- Make them work with non Aero based Windows themes
- Make them click-through without the requirement to disable GPU

**Comment by jtg-gg** [comment]
@TheRealDannyyy transparency was an experimental feature, I personally not using it anymore, so won't spend more time in developing it (i.e. supporting non aero)

as for disable gpu, it is only the compositing
for click through to work the final composited result must be in main memory (CPU memory)
so either you just do the compositing by CPU, or if you really want GPU compositing, you can copy back the GPU texture to CPU, but these require more work, and GPU texture read is very very slow on most GPU, so it is not very useful

**Comment by TheRealDannyyy** [comment]
@jtg-gg Thanks for all the information.
Despite not activly working on it anymore, would you consider porting the existing features over to the new window system or will this whole feature be removed?

**Comment by rogerwang** [comment]
@TheRealDannyyy the transparency features have been ported to nw2 mode.

**Comment by tolrtd** [comment]
@rogerwang with 0.35.4, any windows opened with nw.Window.open are producing errors that nw is not defined.  Is there another flag to force these new Chrome windows to be in nw context - or maybe don't use nw.Window.open anymore?

**Comment by rogerwang** [comment]
@tolrtd could you please provide a reproduce? It works for me.

**Comment by tolrtd** [comment]
@rogerwang I think it is when you have "show": false in the window manifest.  In the attached example the Main Window should open fine, but the Child Window does not (on my Win 10 x64, SDK version, it freezes and does either white screen or sometimes black screen, no frame)


[nwjs-5875-test.zip](https://github.com/nwjs/nw.js/files/2753145/nwjs-5875-test.zip)

**Comment by rogerwang** [comment]
@tolrtd I just fixed it in git and it will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by Blatman** [comment]
Just discovered that using a nativemenu on Mac OS will break CMD-Q/Quit from menubar
Updated test app attached - it starts on index-simple.html and uses osxmenu.js

Essential code -
var nw,
    win = nw.Window.get();

var nativeMenuBar = new nw.Menu({
    type: "menubar"
});

nativeMenuBar.createMacBuiltin('appname', {
});

win.menu = nativeMenuBar;  // CMD-Q works ok if this line remmed out


[nw2testmenu.zip](https://github.com/nwjs/nw.js/files/2772289/nw2testmenu.zip)

**Comment by rogerwang** [comment]
@Blatman Thanks. Fixed only on nw36 branch since it's the new nightly and will be the next release.

**Comment by rogerwang** [comment]
@TheRealDannyyy thanks. Will fix those issues.

**Comment by TheRealDannyyy** [comment]
Referencing #5337 for potential future fix.

**Comment by Blatman** [comment]
@rogerwang   Would it be worth pinning this issue until closed since it is P1 and a new feature? - it tends to get lost in the issues list and folk are creating separate issues that relate to the nw2 switch.

**Comment by rogerwang** [comment]
@Blatman done

**Comment by TheRealDannyyy** [comment]
@rogerwang I've tested the most recent nw.js v0.37.1 release and there is still one small fullscreen issue left. Moving the mouse pointer to top of the screen still displays the "X" button.

I believe this feature has a flag so it might just require that flag to be disabled by default.

![fullscreenclose](https://user-images.githubusercontent.com/15656049/55176350-444c6880-5181-11e9-83b8-bb84b47c2334.PNG)

**Comment by rogerwang** [comment]
@TheRealDannyyy I just fixed the fullscreen button issue in git. It will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by TheRealDannyyy** [comment]
@rogerwang Thanks for the fix! Can confirm that all fullscreen issues have been fixed.

The only major issue left is the window dimension issue as previously mentioned. If you could fix or provide a workaround for that would be amazing. (Tested using **NWjs v0.37.4** and this [Resolution_Test.zip](https://github.com/nwjs/nw.js/files/3080676/Resolution_Test).)

_Reproduction:_
1. Run with most recent version of NW.js
2. Notice wrong window dimensions being used
(Left and right sides of the canvas.)

_Screenshot:_
![Issue](https://user-images.githubusercontent.com/15656049/56142125-65dd8a80-5f9e-11e9-83ad-17da74cf1274.PNG)

**Comment by rogerwang** [comment]
@TheRealDannyyy I don't notice any difference under the 2 modes with 0.38.0. Could you try again?

**Comment by TheRealDannyyy** [comment]
@rogerwang I can still reproduce using nw.js v0.38.1, nothing has changed for me.

**Comment by Blatman** [comment]
@rogerwang - FWIW I tried the test zip with 0.38.2-sdk and get the same as screenshot above but only if nw2 enabled in manifest - just get a black cross without nw2 which I guess is the desired outcome.
10.13.6 used.

**Comment by Blatman** [comment]
Just noticed - maybe a patch still to go into alpha build? 
High Sierra 10.13.6 

Using 0.39.0a1 I get Uncaught TypeError: win.getPrinters is not a function - was OK on 0.38.2 and earlier. Works OK without nw2 feature enabled. Normally should get a printer json object if win.getPrinters(console.log) done.

[winGetPrinters Bug.zip](https://github.com/nwjs/nw.js/files/3147187/winGetPrinters.Bug.zip)

**Comment by Blatman** [comment]
Bonza - getPrinters works fine

**Comment by Blatman** [comment]
Getting Uncaught Errors concerning onDocument properties with 0.39 (only with nw2 enabled) - not sure if this is going to be a problem ....
No errors if 0.38.4 is used.

<img width="1450" alt="error" src="https://user-images.githubusercontent.com/11089335/58079229-6e7e3d80-7ba8-11e9-921c-0b195dae8606.png">

Test app will show errors in background-context

[nw2test.zip](https://github.com/nwjs/nw.js/files/3201418/nw2test.zip)

**Comment by Blatman** [comment]
@rogerwang - not sure if this last commit was meant to address the Uncaught errors (BLESSED_EXTENSION) but still happens with latest build (Index of /live-build/nw39/06-05-2019/9836f0de6/). Note: the errors have occurred since the first 0.39a1 build.

**Comment by TheRealDannyyy** [comment]
@rogerwang Will this be enabled by default in the next NW.js v0.40.0 stable release?

**Comment by rogerwang** [comment]
@TheRealDannyyy unfortunately no... It was the plan, but it was delayed due to API implementation rework in 0.39.0 to cope with upstream change in Chrome 75.  

The nightly tests under NW2 mode was integrated in the [buildbot](http://buildbot-master.nwjs.io:8010/waterfall) and there are a few tests failing. It will be released after those failure are resolved.

**Comment by TheRealDannyyy** [comment]
Alright, thanks for the info.

**Comment by jtg-gg** [comment]
@rogerwang I found another issue with nw40 using "nw2"
in Windows, if the nw.js app has several windows, closing all window using right click from taskbar, will close all but 1 window

this doesn't happen with nw39

**Comment by rogerwang** [comment]
Will fix it soon. Thanks for the report.

**Comment by Blatman** [comment]
MacOS 10.13.6 - tested with 0.41.2-sdk and 0.38.4-sdk.

Appears to be a wee anomaly with win.on('close', etc.
Have attached a test sample which will work OK if nw2 not used or pre-nw2 build of nwjs (eg: 0.38.4) is used. Run the sample and use the Application Readme menu - on close the hide/show will work fine but the close gives an error -
Unchecked runtime.lastError: cannot find browser window

[wintest-nw2changes basic.zip](https://github.com/nwjs/nw.js/files/3639588/wintest-nw2changes.basic.zip)

Bad example -
![bad](https://user-images.githubusercontent.com/11089335/65385611-df855b80-dd28-11e9-9f9e-c8f322062088.jpg)

Good example -
![good](https://user-images.githubusercontent.com/11089335/65385615-ec09b400-dd28-11e9-8c8c-1ac78fb4a2a0.jpg)

**Comment by TheRealDannyyy** [comment]
Hi @rogerwang.

I'm trying to use the chromium args: "--enable-features=nw2 --start-maximized".
NWjs doesn't start maximized as expected. Is this a bug or not supported?

**Comment by TheRealDannyyy** [comment]
Any progress on this? Only 4 SDK builds seem to be failing to build still.

NW2 fixes a lot of issues with 3rd party apps like Steam. Would really like this to be shipped by default so I don't have to use the flag anymore.

**Comment by rogerwang** [comment]
@TheRealDannyyy could you please list some of the issues it fixed on your side?

The next step would be look into the test regressions in NW2 mode, which is 5 more test case failures according to the CI. Once they are fixed the NW2 mode can be switched to default.

It will begin soon with the rework described in https://github.com/nwjs/nw.js/issues/5875#issuecomment-513270200 stablized in recent versions.

**Comment by TheRealDannyyy** [comment]
Some of things that NW2 seems to improve or even fix:
- Older systems display weird inner-bounds window content
- Some 3rd party recorders are able to record the window
- Slightly faster startup (before the startup performance regression)

I didn't report the window content issue yet, since it seems to be really specific. I could just recently manage to reproduce it on my Win7 system. Win10 doesn't seem to be affected. Again, NW2 doesn't have this issue at all.

![unknown](https://user-images.githubusercontent.com/15656049/68311645-1d102f00-00b2-11ea-947a-a77e7f6f23a3.png)

**Comment by rogerwang** [comment]
> I found another issue with nw40 using "nw2"
> in Windows, if the nw.js app has several windows, closing all window using right click from taskbar, will close all but 1 window

@jtg-gg I can't reproduce this with latest build: http://dl.nwjs.io/live-build/nw42/11-06-2019/c0bcf795f/v0.42.3/ . Could you please confirm? If it still breaks on your side, please provide a sample. Thanks.

**Comment by jtg-gg** [comment]
@rogerwang thank youm the issue has been fixed

**Comment by Blatman** [comment]
Excellent - win.close now works well with 0.42.3 and the BLESSED EXTENSION logs disappeared in an earlier build.
Just tried 0.42.3 on the resolution bug found above by @TheRealDannyyy (using Resolution_Test.zip) and it still fails with black edges on left and right but is OK if nw2 disabled in manifest.
Cheers.

**Comment by TheRealDannyyy** [comment]
I found a regression regarding the window icon. It's not being applied and displays a corrupted icon inside the taskbar. I couldn't reproduce this using NW1 on Windows 7, could also affect NW1 on newer OS's.

**Project for reproduction:** [NW2_NoIconTest.zip](https://github.com/nwjs/nw.js/files/3825576/NW2_NoIconTest.zip)

**Steps:** 
1. Run project using NWjs 0.42.0+ on Windows
2. Wait for startup and loading to finish
3. Notice "Construct 2" icon not being applied and corrupted icon

**Screenshot:** 
![NW2_NoIcon](https://user-images.githubusercontent.com/15656049/68497524-06eea400-0255-11ea-8d9e-ddaaef20a8c0.png)

**Comment by rogerwang** [comment]
Latest build: https://dl.nwjs.io/live-build/nw42/11-13-2019/84f82c545/v0.42.4/ with the fix for icon and dimension.

@TheRealDannyyy @Blatman the window dimension is tested with cases in https://github.com/nwjs/nw.js/tree/nw42/test/sanity/issue5093-window-size-match-package-json and https://github.com/nwjs/nw.js/tree/nw42/test/sanity/issue4221-win-open-manifest etc.

In your case `Resolution_Test.zip` the given window size seems to be changed by C2 runtime somehow -- even with the good case under nw1 mode, the created window's dimension is different with package.json. So I don't use it in my test.

**Comment by Blatman** [comment]
@rogerwang - Tried out the build above for the window dimension and I find a difference between the main window and sub windows (in this case opened from the native menu). In the osxmenu.js the nw.Window.open parameters are set for 800 and 600 as they are in the manifest for the main window.
 
I've attached a test case using the 5093 test parameters as above which shows the main window overall height including the title bar as 600px but the same html will open in a window from the menu as 622px (600 + the title bar). Should this be the case?

[Window-Size-test.zip](https://github.com/nwjs/nw.js/files/3841310/Window-Size-test.zip)

<img width="1657" alt="difference" src="https://user-images.githubusercontent.com/11089335/68767384-85ae5d00-0618-11ea-888d-2da9402c407f.png">

**Comment by rogerwang** [comment]
@Blatman it should be a bug -- they should be the same and the parameter should be the inner dimension. And it's interesting to see the test on the MacOS CI machine was passed ...

**Comment by TheRealDannyyy** [comment]
@rogerwang Can confirm the icon fix. Also thanks and thanks for releasing NW2!

The resolution test as you mentioned still fails, not sure if you can fix it at this point.
The creator of C2 actually [gave me a "hack"](https://www.construct.net/en/forum/construct-3/general-discussion-7/construct-team-please-reveal-146858?utm_campaign=forumtopicemailsub&utm_medium=email&utm_source=987539&utm_term=txt3-read-nepeo%2527s-post#forumPost987512) that the runtime might be using already. I'm not sure if that'll help to come up with a built-in workaround but that hack seems to work.

**Comment by TheRealDannyyy** [comment]
This doesn't seem to be a major problem but NWjs v0.42.4 generated a log file with an error inside.
[debug.log](https://github.com/nwjs/nw.js/files/3842146/debug.log)

**Comment by Blatman** [comment]
Corker - 0.42.5 does the job nicely, win height parameter is the inner dimension on all windows.
Thanks

**Comment by Blatman** [comment]
0.42.5-sdk OSX High Sierra (10.13.6)

Seems to be an issue using win.setAlwaysOnTop(true); during runtime.
Works OK with nw2 disabled and will work if set as a win.open parameter in manifest.
Can be tested with Window-Size-test.zip above - just add win.setAlwaysOnTop(true); at end of osxmenu.js

**Comment by TheRealDannyyy** [comment]
Unrelated question. Would it be a good idea to close this issue now and create individual issues for NW2 related bugs? Might make issues easier to sort out and reproduce.

**Comment by Blatman** [comment]
0.42.6-sdk OSX High Sierra (10.13.6)

Was trying to rework a transparent app and unable to get rid of window shadow - found this also to be the case with normal framed windows as well. I tried using win.setShadow(false) in the js and the app just crashes on startup with trap 14. 

To reproduce just add win.setShadow(false) to the end of the osxmenu.js in the Window-Test app above - the disabling of the shadow will work OK with nw2 disabled.

**Comment by rogerwang** [comment]
Yes. I'm closing this issue as it would be easier to follow individual issues. Please file individual issues for nw2. Thanks.

**Comment by anesuc** [comment]
I am not sure if I need to start a new issue on this, but I can't access variables I set in the winndow (NWindow) variable from parent vise-versa. This took me DAYS to figure out that this was the issue since this was crashing everything including Devtools on my project. Kinda important now since this is now the default implementation.
