### ISSUE TITLE
play video with ' undefined is not a function' error

### ISSUE THREAD

**Issue by itlodge** [nwjs/nw.js#2265]
Hi,

When I update node-webkit to 0.10.2, my app crash with an error:

```
TypeError: undefined is not a function
```

in a line of code:

```
video.play();
```

So I write a simple app for testing.

```
<html>
  <head>
    <title>test</title>
  </head>
  <body>
    <video id="video">
      <source src="http://vjs.zencdn.net/v/oceans.mp4" type="video/mp4"/>
    </video>
    <script type="text/javascript">
      document.getElementById('video').play(); 
    </script>
  </body>
</html>
```

If you run this code, it will produce the same error.

When I change the code to this one:

```
<html>
  <head>
    <title>test</title>
  </head>
  <body>
    <view id="view"></view>
    <script type="text/javascript">
      var view = document.getElementById('view');
      var video = document.createElement('video');
      video.controls = true;
      video.autoplay = true;
      var source = document.createElement('source');
      source.src = 'http://vjs.zencdn.net/v/oceans.mp4';
      source.type = 'video/mp4';
      video.appendChild(source);
      view.appendChild(video);
      //video.play(); 
    </script>
  </body>
</html>
```

The code displayed in the developer tools is:

```
<view id="view">
  <video>
    <source>
  </video>
</view>
```

All the attributes of tag video and source are gone!

What's wrong? Is the bug of node-webkit or others?

-----more information-------
node version: v0.11.14-pre
OS: Arch Linux x86_64
