### ISSUE TITLE
app 'open' event never fires

### ISSUE THREAD

**Issue by ferbs** [nwjs/nw.js#866]
node-webkit v 0.6.0 never seems to trigger 'open'. I'm trying to use it as described on https://github.com/rogerwang/node-webkit/wiki/Handling-files-and-arguments

```javascript
require('nw.gui').App.on('open', function(pathData) {
  // never reached, even when open is called on an existing/launched app
});
```

**Comment by rogerwang** [comment]
should be working with latest 0.13 version.

**Comment by sumit6b** [comment]
I am using 

```require('nw.gui').App.on('open', function(pathData) {
  // never reached, even when open is called on an existing/launched app
});
```

But I am getting
```
VM979:1 Uncaught TypeError: nw.gui.App.listeners is not a function
    at eval (eval at evaluate (unknown source), <anonymous>:1:12)
    at Object.InjectedScript._evaluateOn (<anonymous>:878:55)
    at Object.InjectedScript._evaluateAndWrap (<anonymous>:811:34)
    at Object.InjectedScript.evaluateOnCallFrame (<anonymous>:936:21)
```
