### ISSUE TITLE
Cannot build with gcc 4.7.0

### ISSUE THREAD

**Issue by zcbenz** [nwjs/nw.js#9]
Got this error when compiling:

```
In file included from seccompsandbox/library.cc:7:0:
seccompsandbox/library.h:159:46: error: ‘ssize_t’ has not been declared
make: *** [out/Debug/obj.target/seccomp_sandbox/seccompsandbox/library.o] Error 1
make: *** Waiting for unfinished jobs....
```

This bug was caused by not including `unistd.h`, which was not revealed by compiler until gcc 4.7.

Upstream `chromium` also had bugs of this type, see http://code.google.com/p/chromium/issues/detail?id=120724&can=1&q=GCC%204.7&colspec=ID%20Pri%20Mstone%20ReleaseBlock%20Area%20Feature%20Status%20Owner%20Summary
