### ISSUE TITLE
use of undeclared identifier 'TypedArray'

### ISSUE THREAD

**Issue by fov42550564** [nwjs/nw.js#1274]
I want to use gl.readPixels to read rgba to a Uint8Array, then transport pixels to c++ addon, in c++ addon transfer rgba to yuv data, but when I use node-gyp build, it show the error:error: no member named 'Uint8Array' in namespace 'v8'.
Handle Opengl::RGBA2YUV(const Arguments& args) {
HandleScope scope;
Local arg = args[0];
Localv8::Uint8Array typedArray = Localv8::Uint8Array::Cast(arg);
......
}

**Comment by rogerwang** [comment]
This should be working with latest 0.13 version now.
