### ISSUE TITLE
WebSocket (client) does not working in v0.11.5(OSX 10.10.1, xcode 6.1.1, npm 1.4.9)

### ISSUE THREAD

**Issue by ruanjf** [nwjs/nw.js#2973]
`$ which node`
`/usr/local/opt/nvm/v0.11.13/bin/node`

`$ which node-gyp`
`/usr/local/opt/nvm/v0.11.13/lib/node_modules/npm/bin/node-gyp-bin/node-gyp`

`$ node-gyp -v`
`v0.13.0`

install ws
`$ npm install ws`
```
> ws@0.6.5 install /Users/rjf/project/gateway-nw/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
ws@0.6.5 node_modules/ws
├── options@0.0.6
├── ultron@1.0.1
└── nan@1.4.3
```

Test code
```
  var WebSocket = require('ws');
  var ws = new WebSocket('ws://echo.websocket.org');
  console.log(ws)
```

log
```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v86Object3SetENS_6HandleINS_5ValueEEES3_NS_17PropertyAttributeE
  Referenced from: /Users/rjf/project/gateway-nw/node_modules/ws/build/Release/bufferutil.node
  Expected in: dynamic lookup

dyld: Symbol not found: __ZN2v86Object3SetENS_6HandleINS_5ValueEEES3_NS_17PropertyAttributeE
  Referenced from: /Users/rjf/project/gateway-nw/node_modules/ws/build/Release/bufferutil.node
  Expected in: dynamic lookup
```

**Comment by rogerwang** [comment]
Did you rebuild it against nw? See https://github.com/nwjs/nw.js/wiki/Build-native-modules-with-nw-gyp

**Comment by ruanjf** [comment]
Thank  , after rebuild it was work
