### ISSUE TITLE
plugins not working with 0.12

### ISSUE THREAD

**Issue by smolleyes** [nwjs/nw.js#3195]
hi

i tried

"webkit": {
    "plugin": true
  }

and 

 "chromium-args": "--load-plugin=plugins/npWebChimera.so"

but navigator.plugins array is always empty , an idear? (i m on ubuntu 14.04 64 bits)

thanks
##

**Comment by sechrist** [comment]
NPAPI plugins aren't available within Chromium past version 35 (NW 0.10.5).

**Comment by smolleyes** [comment]
hi

i know it s not ppapi plugins, no plugins load at all

thx

**Comment by TemaSM** [comment]
Confirming that. I can't configure to work any 'npm' plugin for newer version (0.12), but on previous version everything was working fine!
Chromium console saying:
Uncaught Error: Module did not self-register. | module.js:346
(rebuilding with 'node-gyp' and 'nw-gyp' not bringing any good results, additionally i noticed some compilation errors via 'nw-gyp')

**Comment by sechrist** [comment]
@TemaSM you're talking about node modules, which aren't referred to as plugins within this context.

@smolleyes Only PPAPI plugins are going to work with Linux after Chromium 35. Your paste of npWebChimera.so shows an NPAPI plugin.

**Comment by mscreenie** [comment]
See this: http://blog.chromium.org/2014/11/the-final-countdown-for-npapi.html

Chrome 41 removed support for NPAPI plugins. Only PPAPI plugins can be used. nw12 is based on Chrome 41 stable.

**Comment by TemaSM** [comment]
@sechrist Anyway, node modules stopped working with new version. I don't why, but rebuilding not helping at all - it's very boring.

**Comment by jaruba** [comment]
Which is the last NW version that still supports NPAPI plugins on Linux?

**Comment by mscreenie** [comment]
I'd check the Chrome blogs out, my previous post may be incorrect. NPAPI may still work with Chrome 41.

"In April 2015 NPAPI support will be disabled by default in Chrome and we will unpublish extensions requiring NPAPI plugins from the Chrome Web Store. Although plugin vendors are working hard to move to alternate technologies, a small number of users still rely on plugins that haven’t completed the transition yet. We will provide an override for advanced users (via chrome://flags/#enable-npapi) and enterprises (via Enterprise Policy) to temporarily re-enable NPAPI while they wait for mission-critical plugins to make the transition."

**Comment by fritx** [comment]
How to use plugins?

**Comment by jaruba** [comment]
@fritx https://github.com/nwjs/nw.js/wiki/Third-party-browser-plugins

**Comment by fritx** [comment]
it worked in nw0.10.5 (chromium35), but broke in nw0.12
![image](https://cloud.githubusercontent.com/assets/6647633/9784684/4f301d72-57df-11e5-9a5e-def035849d3a.png)
@jaruba how can i continue this plugin in new versoin?

**Comment by jaruba** [comment]
@fritx Try adding the plugin files in the `plugins` folder that you should create in the root path of your app.

Then try adding these lines to your `package.json`:

    "chromium-args": "--load-plugin=plugins\\npUdCapture.dll",
    "webkit": {
        "plugin": true
    }

If that doesn't work, then I don't have any other suggestions for you. :)

**Comment by Christywl** [comment]
Is this issue still reproduced on the latest nwjs build? If so, could you please provide a sample to reproduce it?

**Comment by Christywl** [comment]
close until there is more information.
