### ISSUE TITLE
[nw13] nw.require fails to load modules

### ISSUE THREAD

**Issue by hkaya** [nwjs/nw.js#3763]
Hi all,

I'm having trouble using the new `require`. It seems like my app can't load any third-party dependencies. Also, `fs` is acting odd which makes me think this is a permission problem. I'm using `nwjs-sdk-v0.13.0-alpha3-linux-x64`. When I'm in the app directory I can run the app by `/path/to/nw .` and that opens up the nw window as expected. However, `nw.require` fails to load any modules whether they are local or installed using npm. Any ideas?

Here are the app files:
```bash
$ ls -p
index.html  index.js  node_modules/  package.json  test.js
$ ls -p node_modules
lodash/
```

package.json:
```json
{
  "name": "test-app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "dependencies": {
    "lodash": "^3.10.1"
  },
  "permissions": [
      "node",
      "fileSystem"
  ]
}
```

index.js:
```javascript
chrome.app.runtime.onLaunched.addListener(function() {
  chrome.app.window.create('index.html', {
    id: 'main',
    bounds: { width: 620, height: 500 }
  });
});
```

index.html:
```html
<!DOCTYPE html>
<html>
<head>
  <script type="text/javascript">
    var fs = nw.require('fs');

    console.log(fs.readdirSync('.')); // prints []
    console.log(fs.readdirSync('..')); // prints []
    console.log(fs.readdirSync('/')); // prints []
    //console.log(fs.readdirSync('/tmp')); // throws ENOENT
    // var _ = nw.require('lodash'); // cannot find module
    nw.require('./test.js'); // cannot find module
    // nw.require('/absolute/path/to/test.js'); // cannot find module
  </script>
</head>
<body>
    Hello.
</body>
</html>
```

test.js:
```javascript
var test = function() {
    console.log('in test.js');
}

module.exports = test
```

**Comment by maxbarry** [comment]
Same here with nwjs-sdk-v0.13.0-alpha2-linux-x64 on Ubuntu 15.04.

Can't load any custom or third-party module, no matter what string I pass to nw.require().

    > var m = nw.require('gulp')
    module.js:341 Uncaught Error: Cannot find module 'gulp'
      at Function.Module._resolveFilename (module.js:341:15)
      at Function.Module._load (module.js:286:25)
      at Module.require (module.js:370:17)
      at require (module.js:389:17)
      at <anonymous>:2:12
      at Object.InjectedScript._evaluateOn (<anonymous>:905:140)
      at Object.InjectedScript._evaluateAndWrap (<anonymous>:838:34)
      at Object.InjectedScript.evaluate (<anonymous>:694:21)

**Comment by maxbarry** [comment]
I did a bit of stracing.

When running the app from /home/max/code/myApp/ and executing:

    var m = nw.require('gulp')

... this shows up in strace:

    stat("//node_modules", 0x7ffc3a00ea20)  = -1 ENOENT (No such file or directory)
    stat("/node_modules", 0x7ffc3a00ea20)   = -1 ENOENT (No such file or directory)
    stat("/home/max/.node_modules", 0x7ffc3a00ea20) = -1 ENOENT (No such file or directory)
    stat("/home/max/.node_libraries", 0x7ffc3a00ea20) = -1 ENOENT (No such file or directory)
    stat("/lib/node", 0x7ffc3a00ea20)       = -1 ENOENT (No such file or directory)

It never seems to check /home/max/code/myApp/node_modules/, which is where gulp actually lives.

When trying to require a custom module:

    var m = nw.require('./js/Game')

... these lines appear in strace:

    gettid()                                = 1
    getcwd("/", 4096)                       = 2
    stat("/home/max/code/myApp", 0x7ffc3a00ea20) = -1 ENOENT (No such file or directory)
    [...]
    open("/proc/self/maps", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

The stat() result is a bit puzzling to me since that directory definitely exists, and has the usual permissions, and is owned by the same user ("max") as runs nwjs. Similarly, /proc/self/maps does exist and is readable by user "max".

**Comment by rogerwang** [comment]
This should be fixed in alpha7. Could you please try again?

**Comment by maxbarry** [comment]
This now works in alpha7:
```javascript
var m = nw.require('gulp')
```
I still can't get my own modules to load, though, if they live outside node_modules/:
```javascript
> var m = nw.require('./js/Code')
module.js:343 Uncaught Error {code: "MODULE_NOT_FOUND", message: "Cannot find module './js/Code'"}
```
I haven't been following whether this is supposed to work in 0.13... maybe the required format has changed? It works in 0.12.

**Comment by maxbarry** [comment]
Hooray! Loading own modules works in nwjs-sdk-v0.13.0-beta1-linux-x64 on Ubuntu 15.04. Thanks!
