### ISSUE TITLE
webview.showDevtools(show, container) does not work on v0.35.2

### ISSUE THREAD

**Issue by hhhoney** [nwjs/nw.js#6903]
on v0.35.2 (SDK, macOS Mojave, node 11.4.0), webview.showDevtools(show) works, but webview.showDevtools(show, container) throws an error:

```
Uncaught TypeError: container.getGuestId is not a function
    at ChromeWebViewImpl.WebViewImpl.showDevTools (extensions::webView:229)
    at HTMLElement.showDevTools (extensions::guestViewContainerElement:141)
```

Reproduce Demo:
[webview.zip](https://github.com/nwjs/nw.js/files/2689498/webview.zip)

Debug screenshot [extensions::webview]:
<img width="809" alt="getguestid" src="https://user-images.githubusercontent.com/45038433/50140239-0963aa80-02df-11e9-9a2b-ad5cc46eaa8d.png">

**Comment by rogerwang** [comment]
This is fixed in git and will be available in the next [nightly build](http://dl.nwjs.io/live-build/).

**Comment by rogerwang** [comment]
https://dl.nwjs.io/live-build/nw35/12-19-2018/7c0df2185/v0.35.3/
